<?php

namespace Flux\Schema;

use Flux\Repository\FluxRepository;
use SilverStripe\Core\Config\Config;
use SilverStripe\ORM\DataObject;

/**
 * Read-only view over the YAML/Config-defined flux_fields,
 * flux_fieldtypes and flux_relation_fields for any DataObject class.
 *
 * Pure: no request state, no DataObject instances required.
 * Generated by `sake flux:generate-config` and reloaded with `?flush=1`.
 */
class FluxSchema
{
    /**
     * Schema slice for a single class.
     *
     * @return array{Fields: array, RelationFields: array}
     */
    public function forClass(string $className): array
    {
        if (!class_exists($className) || !is_subclass_of($className, DataObject::class)) {
            return ['Fields' => [], 'RelationFields' => []];
        }

        $config = Config::forClass($className);

        return [
            'Fields' => $this->collectFields($config),
            'RelationFields' => $this->collectRelationFields($config),
        ];
    }

    /**
     * Schema slice for multiple classes, keyed by class name.
     */
    public function forClasses(array $classNames): array
    {
        $out = [];
        foreach (array_unique($classNames) as $class) {
            $out[$class] = $this->forClass($class);
        }
        return $out;
    }

    private function collectFields($config): array
    {
        $fluxFields = $config->get('flux_fields');
        if (!$fluxFields) {
            return [];
        }

        $fields = [];
        foreach ($fluxFields as $key => $bind) {
            $type = FluxRepository::getFluxDataType($key, $config);
            if (!$type) {
                continue;
            }

            $fields[$key] = [
                'key' => $key,
                'bind' => $bind,
                'type' => $type,
            ];
        }

        return $fields;
    }

    /**
     * Returns relation field definitions without runtime data (no IDs, no actions).
     * Runtime data is layered on by FluxContextResolver when it has a DataObject.
     */
    private function collectRelationFields($config): array
    {
        $relationFields = $config->get('flux_relation_fields');
        if (!$relationFields) {
            return [];
        }

        $out = [];
        foreach ($relationFields as $relationName => $entry) {
            $dropZone = null;
            $sortable = false;

            if (is_string($entry)) {
                $selector = $entry;
                $explicitFields = null;
            } else {
                $selector = $entry['DOMSelector'] ?? null;
                $explicitFields = $entry['Fields'] ?? null;
                $dropZone = $entry['DropZone'] ?? null;
                $sortable = (bool) ($entry['Sortable'] ?? false);
            }

            if (!$selector) {
                continue;
            }

            $slice = [
                'selector' => $selector,
                'Fields' => $this->resolveRelationFields($config, $relationName, $explicitFields),
            ];

            if ($dropZone) {
                $slice['dropZone'] = $dropZone;
            }
            if ($sortable) {
                $slice['sortable'] = true;
            }

            $out[$relationName] = $slice;
        }

        return $out;
    }

    private function resolveRelationFields($config, string $relationName, ?array $explicitFields): array
    {
        $relatedClass = $this->resolveRelationClass($config, $relationName);
        if (!$relatedClass) {
            return [];
        }

        $relatedConfig = Config::forClass($relatedClass);
        $fieldMap = $explicitFields ?? ($relatedConfig->get('flux_fields') ?? []);

        $fields = [];
        foreach ($fieldMap as $fieldName => $bind) {
            $type = FluxRepository::getFluxDataType($fieldName, $relatedConfig);
            if (!$type) {
                continue;
            }
            $fields[$fieldName] = ['bind' => $bind, 'type' => $type];
        }

        return $fields;
    }

    private function resolveRelationClass($config, string $relationName): ?string
    {
        $relations = array_merge(
            $config->get('has_many') ?? [],
            $config->get('many_many') ?? [],
        );

        $relatedClass = $relations[$relationName] ?? null;

        if (is_array($relatedClass)) {
            $relatedClass = $relatedClass['through'] ?? null;
        }

        if (!is_string($relatedClass)) {
            return null;
        }

        if (str_contains($relatedClass, '.')) {
            $relatedClass = explode('.', $relatedClass)[0];
        }

        return class_exists($relatedClass) ? $relatedClass : null;
    }
}
